import type { IndiceData } from "@/app/marches/MarchesClient";

// ─── Données statiques (fallback + base pour le cron) ────────────────────────

export const STATIC_INDICES: IndiceData[] = [
  {
    id: "cac40",
    nom: "CAC 40",
    pays: "France",
    drapeau: "🇫🇷",
    region: "europe",
    description: "Les 40 plus grandes capitalisations cotées sur Euronext Paris.",
    stocks: [
      { rang: 1,  nom: "LVMH",              ticker: "MC.PA",  secteur: "Luxe",          capMds: 312, variation:  0.8, currency: "€", slug: "lvmh" },
      { rang: 2,  nom: "Hermès",             ticker: "RMS.PA", secteur: "Luxe",          capMds: 198, variation:  1.2, currency: "€", slug: "hermes" },
      { rang: 3,  nom: "L'Oréal",            ticker: "OR.PA",  secteur: "Consommation",  capMds: 195, variation:  0.6, currency: "€", slug: "loreal" },
      { rang: 4,  nom: "TotalEnergies",      ticker: "TTE.PA", secteur: "Énergie",       capMds: 145, variation: -0.3, currency: "€", slug: "totalenergies" },
      { rang: 5,  nom: "Schneider Electric", ticker: "SU.PA",  secteur: "Industrie",     capMds: 112, variation:  0.5, currency: "€", slug: "schneider-electric" },
      { rang: 6,  nom: "Sanofi",             ticker: "SAN.PA", secteur: "Santé",         capMds: 108, variation: -0.1, currency: "€", slug: "sanofi" },
      { rang: 7,  nom: "Air Liquide",        ticker: "AI.PA",  secteur: "Chimie",        capMds:  78, variation:  0.2, currency: "€", slug: "air-liquide" },
      { rang: 8,  nom: "BNP Paribas",        ticker: "BNP.PA", secteur: "Finance",       capMds:  72, variation: -0.4, currency: "€", slug: "bnp-paribas" },
      { rang: 9,  nom: "Safran",             ticker: "SAF.PA", secteur: "Aéronautique",  capMds:  68, variation:  0.9, currency: "€", slug: "safran" },
      { rang: 10, nom: "Airbus",             ticker: "AIR.PA", secteur: "Aéronautique",  capMds:  98, variation:  1.8, currency: "€", slug: "airbus" },
    ],
  },
  {
    id: "dax40",
    nom: "DAX 40",
    pays: "Allemagne",
    drapeau: "🇩🇪",
    region: "europe",
    description: "Les 40 plus grandes capitalisations cotées à la Bourse de Francfort.",
    stocks: [
      { rang: 1,  nom: "SAP",             ticker: "SAP.DE",  secteur: "Technologie",      capMds: 260, variation:  0.6, currency: "€", slug: "sap" },
      { rang: 2,  nom: "Siemens",         ticker: "SIE.DE",  secteur: "Industrie",        capMds: 135, variation:  0.4, currency: "€", slug: "siemens" },
      { rang: 3,  nom: "Allianz",         ticker: "ALV.DE",  secteur: "Assurance",        capMds: 120, variation:  0.3, currency: "€", slug: "allianz" },
      { rang: 4,  nom: "Deutsche Telekom",ticker: "DTE.DE",  secteur: "Télécommunications",capMds: 110, variation:  0.1, currency: "€", slug: "deutsche-telekom" },
      { rang: 5,  nom: "Mercedes-Benz",   ticker: "MBG.DE",  secteur: "Automobile",       capMds:  52, variation: -0.4, currency: "€", slug: "mercedes-benz" },
      { rang: 6,  nom: "BMW",             ticker: "BMW.DE",  secteur: "Automobile",       capMds:  55, variation: -0.5, currency: "€", slug: "bmw" },
      { rang: 7,  nom: "BASF",            ticker: "BAS.DE",  secteur: "Chimie",           capMds:  40, variation: -0.2, currency: "€", slug: "basf" },
      { rang: 8,  nom: "Volkswagen",      ticker: "VOW3.DE", secteur: "Automobile",       capMds:  55, variation: -0.8, currency: "€", slug: "volkswagen" },
      { rang: 9,  nom: "Infineon",        ticker: "IFX.DE",  secteur: "Semi-conducteurs", capMds:  38, variation:  1.1, currency: "€", slug: "infineon" },
      { rang: 10, nom: "Adidas",          ticker: "ADS.DE",  secteur: "Mode",             capMds:  33, variation:  0.5, currency: "€", slug: "adidas" },
    ],
  },
  {
    id: "ftsemib",
    nom: "FTSE MIB",
    pays: "Italie",
    drapeau: "🇮🇹",
    region: "europe",
    description: "Les 40 principales capitalisations de la Bourse de Milan.",
    stocks: [
      { rang: 1,  nom: "Ferrari",            ticker: "RACE.MI", secteur: "Automobile",       capMds:  75, variation:  0.9, currency: "€", slug: "ferrari" },
      { rang: 2,  nom: "UniCredit",          ticker: "UCG.MI",  secteur: "Finance",          capMds:  62, variation:  1.2, currency: "€", slug: "unicredit" },
      { rang: 3,  nom: "Enel",              ticker: "ENEL.MI", secteur: "Énergie",          capMds:  62, variation:  0.4, currency: "€", slug: "enel" },
      { rang: 4,  nom: "Intesa Sanpaolo",   ticker: "ISP.MI",  secteur: "Finance",          capMds:  58, variation:  0.8, currency: "€", slug: "intesa-sanpaolo" },
      { rang: 5,  nom: "Eni",              ticker: "ENI.MI",  secteur: "Énergie",          capMds:  44, variation: -0.3, currency: "€", slug: "eni" },
      { rang: 6,  nom: "STMicroelectronics",ticker: "STM.MI",  secteur: "Semi-conducteurs", capMds:  22, variation:  0.6, currency: "€", slug: "stmicroelectronics" },
      { rang: 7,  nom: "Mediobanca",        ticker: "MB.MI",   secteur: "Finance",          capMds:  14, variation:  0.5, currency: "€", slug: "mediobanca" },
      { rang: 8,  nom: "Leonardo",          ticker: "LDO.MI",  secteur: "Aéronautique",     capMds:  24, variation:  1.4, currency: "€", slug: "leonardo" },
      { rang: 9,  nom: "Stellantis",        ticker: "STLA.MI", secteur: "Automobile",       capMds:  22, variation: -1.1, currency: "€", slug: "stellantis" },
      { rang: 10, nom: "Telecom Italia",    ticker: "TIT.MI",  secteur: "Télécommunications",capMds:  6, variation: -0.2, currency: "€", slug: "telecom-italia" },
    ],
  },
  {
    id: "ibex35",
    nom: "IBEX 35",
    pays: "Espagne",
    drapeau: "🇪🇸",
    region: "europe",
    description: "Les 35 plus grandes entreprises cotées sur la Bourse de Madrid.",
    stocks: [
      { rang: 1, nom: "Inditex",         ticker: "ITX.MC",  secteur: "Consommation",      capMds: 120, variation:  0.7, currency: "€", slug: "inditex" },
      { rang: 2, nom: "Iberdrola",       ticker: "IBE.MC",  secteur: "Énergie",           capMds:  88, variation:  0.3, currency: "€", slug: "iberdrola" },
      { rang: 3, nom: "Banco Santander", ticker: "SAN.MC",  secteur: "Finance",           capMds:  78, variation:  0.9, currency: "€", slug: "banco-santander" },
      { rang: 4, nom: "BBVA",           ticker: "BBVA.MC", secteur: "Finance",           capMds:  65, variation:  1.1, currency: "€", slug: "bbva" },
      { rang: 5, nom: "Telefónica",     ticker: "TEF.MC",  secteur: "Télécommunications", capMds: 22, variation: -0.1, currency: "€", slug: "telefonica" },
    ],
  },
  {
    id: "bel20",
    nom: "BEL 20",
    pays: "Belgique",
    drapeau: "🇧🇪",
    region: "europe",
    description: "Les 20 plus grandes capitalisations de la Bourse de Bruxelles.",
    stocks: [
      { rang: 1, nom: "AB InBev",  ticker: "ABI.BR",  secteur: "Boissons",  capMds: 85, variation:  0.3, currency: "€", slug: "ab-inbev" },
      { rang: 2, nom: "UCB",       ticker: "UCB.BR",  secteur: "Santé",     capMds: 32, variation:  1.0, currency: "€", slug: "ucb" },
      { rang: 3, nom: "KBC Group", ticker: "KBC.BR",  secteur: "Finance",   capMds: 28, variation:  0.5, currency: "€", slug: "kbc-group" },
      { rang: 4, nom: "Ageas",     ticker: "AGS.BR",  secteur: "Assurance", capMds:  8, variation:  0.3, currency: "€", slug: "ageas" },
      { rang: 5, nom: "Solvay",    ticker: "SOLB.BR", secteur: "Chimie",    capMds:  5, variation:  0.6, currency: "€", slug: "solvay" },
    ],
  },
  {
    id: "aex",
    nom: "AEX",
    pays: "Pays-Bas",
    drapeau: "🇳🇱",
    region: "europe",
    description: "Les 25 plus grandes capitalisations cotées sur Euronext Amsterdam.",
    stocks: [
      { rang: 1, nom: "ASML",      ticker: "ASML.AS", secteur: "Semi-conducteurs", capMds: 290, variation:  1.5, currency: "€", slug: "asml" },
      { rang: 2, nom: "Shell",     ticker: "SHEL.AS", secteur: "Énergie",          capMds: 185, variation: -0.3, currency: "€", slug: "shell-aex" },
      { rang: 3, nom: "ING Group", ticker: "INGA.AS", secteur: "Finance",          capMds:  48, variation:  0.8, currency: "€", slug: "ing-group" },
      { rang: 4, nom: "Heineken",  ticker: "HEIA.AS", secteur: "Boissons",         capMds:  38, variation: -0.1, currency: "€", slug: "heineken" },
      { rang: 5, nom: "Philips",   ticker: "PHIA.AS", secteur: "Santé",            capMds:  12, variation: -0.5, currency: "€", slug: "philips" },
    ],
  },
  {
    id: "smi",
    nom: "SMI",
    pays: "Suisse",
    drapeau: "🇨🇭",
    region: "europe",
    description: "Les 20 plus grandes capitalisations cotées à la Bourse de Zurich.",
    stocks: [
      { rang: 1,  nom: "Nestlé",           ticker: "NESN.SW", secteur: "Alimentation", capMds: 270, variation:  0.2, currency: "CHF", slug: "nestle" },
      { rang: 2,  nom: "Novartis",         ticker: "NOVN.SW", secteur: "Santé",        capMds: 220, variation:  0.5, currency: "CHF", slug: "novartis" },
      { rang: 3,  nom: "Roche",            ticker: "ROG.SW",  secteur: "Santé",        capMds: 200, variation:  0.3, currency: "CHF", slug: "roche" },
      { rang: 4,  nom: "UBS Group",        ticker: "UBSG.SW", secteur: "Finance",      capMds:  85, variation:  0.8, currency: "CHF", slug: "ubs-group" },
      { rang: 5,  nom: "ABB",              ticker: "ABBN.SW", secteur: "Industrie",    capMds:  65, variation:  0.4, currency: "CHF", slug: "abb" },
      { rang: 6,  nom: "Richemont",        ticker: "CFR.SW",  secteur: "Luxe",         capMds:  65, variation:  1.0, currency: "CHF", slug: "richemont" },
      { rang: 7,  nom: "Zurich Insurance", ticker: "ZURN.SW", secteur: "Finance",      capMds:  62, variation:  0.3, currency: "CHF", slug: "zurich-insurance" },
      { rang: 8,  nom: "Swiss Re",         ticker: "SREN.SW", secteur: "Finance",      capMds:  40, variation: -0.1, currency: "CHF", slug: "swiss-re" },
      { rang: 9,  nom: "Lonza",            ticker: "LONN.SW", secteur: "Santé",        capMds:  35, variation:  0.7, currency: "CHF", slug: "lonza" },
      { rang: 10, nom: "Givaudan",         ticker: "GIVN.SW", secteur: "Chimie",       capMds:  25, variation:  0.2, currency: "CHF", slug: "givaudan" },
    ],
  },
  {
    id: "ftse100",
    nom: "FTSE 100",
    pays: "Royaume-Uni",
    drapeau: "🇬🇧",
    region: "europe",
    description: "Les 100 plus grandes capitalisations de la Bourse de Londres.",
    stocks: [
      { rang: 1,  nom: "AstraZeneca", ticker: "AZN.L",  secteur: "Santé",        capMds: 210, variation:  0.8, currency: "$", slug: "astrazeneca" },
      { rang: 2,  nom: "Shell",       ticker: "SHEL.L", secteur: "Énergie",      capMds: 185, variation: -0.3, currency: "$", slug: "shell" },
      { rang: 3,  nom: "HSBC",        ticker: "HSBA.L", secteur: "Finance",      capMds: 145, variation:  0.2, currency: "$", slug: "hsbc" },
      { rang: 4,  nom: "Rio Tinto",   ticker: "RIO.L",  secteur: "Mines",        capMds:  95, variation:  1.1, currency: "$", slug: "rio-tinto" },
      { rang: 5,  nom: "Unilever",    ticker: "ULVR.L", secteur: "Consommation", capMds: 112, variation:  0.4, currency: "$", slug: "unilever" },
      { rang: 6,  nom: "BHP",         ticker: "BHP.L",  secteur: "Mines",        capMds:  82, variation:  0.9, currency: "$", slug: "bhp" },
      { rang: 7,  nom: "BP",          ticker: "BP.L",   secteur: "Énergie",      capMds:  88, variation: -0.5, currency: "$", slug: "bp" },
      { rang: 8,  nom: "GSK",         ticker: "GSK.L",  secteur: "Santé",        capMds:  78, variation:  0.3, currency: "$", slug: "gsk" },
      { rang: 9,  nom: "Diageo",      ticker: "DGE.L",  secteur: "Boissons",     capMds:  58, variation: -0.2, currency: "$", slug: "diageo" },
      { rang: 10, nom: "Rolls-Royce", ticker: "RR.L",   secteur: "Aéronautique", capMds:  48, variation:  2.3, currency: "$", slug: "rolls-royce" },
    ],
  },
  {
    id: "sp500",
    nom: "S&P 500",
    pays: "États-Unis",
    drapeau: "🇺🇸",
    region: "ameriques",
    description: "Les 500 plus grandes entreprises américaines cotées en Bourse.",
    stocks: [
      { rang: 1,  nom: "Apple",              ticker: "AAPL",  secteur: "Technologie",      capMds: 3100, variation:  1.2, currency: "$", slug: "apple" },
      { rang: 2,  nom: "Microsoft",          ticker: "MSFT",  secteur: "Technologie",      capMds: 2900, variation:  0.8, currency: "$", slug: "microsoft" },
      { rang: 3,  nom: "Nvidia",             ticker: "NVDA",  secteur: "Semi-conducteurs", capMds: 2600, variation:  2.1, currency: "$", slug: "nvidia" },
      { rang: 4,  nom: "Amazon",             ticker: "AMZN",  secteur: "E-commerce",       capMds: 2100, variation:  0.5, currency: "$", slug: "amazon" },
      { rang: 5,  nom: "Alphabet",           ticker: "GOOGL", secteur: "Technologie",      capMds: 1950, variation:  0.3, currency: "$", slug: "alphabet" },
      { rang: 6,  nom: "Meta",               ticker: "META",  secteur: "Réseaux sociaux",  capMds: 1400, variation:  1.5, currency: "$", slug: "meta" },
      { rang: 7,  nom: "Berkshire Hathaway", ticker: "BRK-B", secteur: "Finance",          capMds: 1050, variation: -0.1, currency: "$", slug: "berkshire-hathaway" },
      { rang: 8,  nom: "Eli Lilly",          ticker: "LLY",   secteur: "Santé",            capMds:  780, variation:  0.7, currency: "$", slug: "eli-lilly" },
      { rang: 9,  nom: "Tesla",              ticker: "TSLA",  secteur: "Automobile",       capMds:  720, variation:  3.2, currency: "$", slug: "tesla" },
      { rang: 10, nom: "Broadcom",           ticker: "AVGO",  secteur: "Semi-conducteurs", capMds:  680, variation:  1.1, currency: "$", slug: "broadcom" },
    ],
  },
  {
    id: "nikkei",
    nom: "Nikkei 225",
    pays: "Japon",
    drapeau: "🇯🇵",
    region: "asie",
    description: "Les 225 principales valeurs de la Bourse de Tokyo.",
    stocks: [
      { rang: 1,  nom: "Toyota",             ticker: "7203.T", secteur: "Automobile",   capMds: 280, variation:  0.4, currency: "$", slug: "toyota" },
      { rang: 2,  nom: "Sony",               ticker: "6758.T", secteur: "Électronique", capMds: 110, variation:  0.9, currency: "$", slug: "sony" },
      { rang: 3,  nom: "SoftBank",           ticker: "9984.T", secteur: "Technologie",  capMds:  98, variation:  1.2, currency: "$", slug: "softbank" },
      { rang: 4,  nom: "Keyence",            ticker: "6861.T", secteur: "Industrie",    capMds:  92, variation:  0.3, currency: "$", slug: "keyence" },
      { rang: 5,  nom: "Mitsubishi UFJ",     ticker: "8306.T", secteur: "Finance",      capMds:  95, variation:  0.6, currency: "$", slug: "mitsubishi-ufj" },
      { rang: 6,  nom: "Recruit Holdings",   ticker: "6098.T", secteur: "Services",     capMds:  72, variation:  0.7, currency: "$", slug: "recruit-holdings" },
      { rang: 7,  nom: "Fast Retailing",     ticker: "9983.T", secteur: "Mode",         capMds:  62, variation:  1.4, currency: "$", slug: "fast-retailing" },
      { rang: 8,  nom: "Honda",              ticker: "7267.T", secteur: "Automobile",   capMds:  48, variation: -0.2, currency: "$", slug: "honda" },
      { rang: 9,  nom: "Shin-Etsu Chemical", ticker: "4063.T", secteur: "Chimie",       capMds:  45, variation:  0.5, currency: "$", slug: "shin-etsu-chemical" },
      { rang: 10, nom: "Fanuc",              ticker: "6954.T", secteur: "Robotique",    capMds:  38, variation: -0.1, currency: "$", slug: "fanuc" },
    ],
  },
];
